# Generated by Django 4.2.29 on 2026-03-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_boost_financial_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productboost',
            name='client_budget',
        ),
        migrations.RemoveField(
            model_name='productboost',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='productboost',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='productboost',
            name='external_campaign_id',
        ),
        migrations.RemoveField(
            model_name='productboost',
            name='platform_budget',
        ),
        migrations.RemoveField(
            model_name='productboost',
            name='targeting_data',
        ),
        migrations.AlterField(
            model_name='productboost',
            name='platform',
            field=models.CharField(choices=[('internal', "AfriMarket (page d'accueil)"), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp Status')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
