# Generated by Django 4.2.29 on 2026-03-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_productboost_client_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productboost',
            name='client_budget',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant payé par le client', max_digits=10),
        ),
        migrations.AddField(
            model_name='productboost',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Commission AfriMarket', max_digits=10),
        ),
        migrations.AddField(
            model_name='productboost',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur en cas d'échec"),
        ),
        migrations.AddField(
            model_name='productboost',
            name='external_campaign_id',
            field=models.CharField(blank=True, help_text='ID de campagne Facebook/WhatsApp', max_length=200),
        ),
        migrations.AddField(
            model_name='productboost',
            name='platform_budget',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Montant envoyé à Facebook/WhatsApp', max_digits=10),
        ),
        migrations.AddField(
            model_name='productboost',
            name='targeting_data',
            field=models.JSONField(blank=True, help_text='Données de ciblage (ville, âge, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='platform',
            field=models.CharField(choices=[('internal', "AfriMarket (page d'accueil)"), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp Status')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
