# Generated by Django 6.1.1 on 2026-10-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_productboost_client_budget_productboost_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productboost',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Commission Comptoir', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productboost',
            name='platform',
            field=models.CharField(choices=[('internal', "Comptoir (page d'accueil)"), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp Status')], max_length=20),
        ),
    ]
