# Generated by Django 6.1.1 on 2026-10-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_libelles_comptoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='cash_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
