# Generated by Django 4.2.29 on 2026-03-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_latitude_store_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp avec indicatif pays (ex: 237677123456)', max_length=20),
        ),
    ]
