# Generated by Django 6.1.1 on 2026-09-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storerole_storemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='Ex: Lun-Sam 8h-18h', max_length=200),
        ),
    ]
