# Generated by Django 6.1.1 on 2026-09-21 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_store_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storemember',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Salaire mensuel brut (F)', max_digits=12),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=0, default=0, help_text='Primes', max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=0, default=0, help_text='Retenues', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('paid', 'Payé')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='store.storemember')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('member', 'month', 'year')},
            },
        ),
    ]
