# Generated by Django 6.1.1 on 2026-09-21 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storemember_salary_payslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('bonus', 'Prime'), ('deduction', 'Retenue')], max_length=20)),
                ('label', models.CharField(help_text='Ex: Prime de transport, Assurance maladie', max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.payslip')),
            ],
        ),
    ]
