# Generated by Django 6.1.1 on 2026-09-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletters', to='marketing.promocode'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='target_audience',
            field=models.CharField(default='customers', help_text='all, customers', max_length=50),
        ),
    ]
