# Generated by Django 6.1.1 on 2026-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stockmovement_warehouse'),
        ('marketing', '0002_newsletter_promo_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='catalog.product'),
        ),
    ]
