# Generated by Django 6.1.1 on 2026-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_newsletter_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='custom_recipients',
            field=models.TextField(blank=True, help_text='Emails personnalisés, un par ligne'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='target_audience',
            field=models.CharField(default='customers', help_text='all, customers, custom', max_length=50),
        ),
    ]
