# Generated by Django 6.1.1 on 2026-09-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_newsletter_custom_recipients_and_more'),
        ('store', '0008_payslipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_amount', models.IntegerField(default=1000, help_text='1 point gagné par tranche de X FCFA')),
                ('silver_threshold', models.IntegerField(default=2000)),
                ('silver_rate', models.IntegerField(default=5, help_text='Réduction en %')),
                ('gold_threshold', models.IntegerField(default=5000)),
                ('gold_rate', models.IntegerField(default=10)),
                ('platinum_threshold', models.IntegerField(default=10000)),
                ('platinum_rate', models.IntegerField(default=15)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_settings', to='store.store')),
            ],
        ),
    ]
