# Generated by Django 6.1.1 on 2026-09-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stockmovement_warehouse'),
        ('marketing', '0005_loyaltysettings'),
        ('store', '0008_payslipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], default='whatsapp', max_length=20)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('customers', 'Mes clients'), ('custom', 'Liste importée')], default='customers', max_length=20)),
                ('custom_numbers', models.TextField(blank=True, help_text='Numéros importés, un par ligne')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('in_progress', 'En cours'), ('done', 'Terminée')], default='draft', max_length=20)),
                ('sent_numbers', models.TextField(blank=True, help_text='Numéros déjà envoyés, un par ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='messaging_campaigns', to='catalog.product')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_campaigns', to='marketing.promocode')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_campaigns', to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
