# Generated by Django 6.1.1 on 2026-09-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stockmovement_warehouse'),
        ('marketing', '0006_messagingcampaign'),
        ('store', '0008_payslipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre interne', max_length=200)),
                ('content', models.TextField(help_text='Texte du post')),
                ('hashtags', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='facebook_posts', to='catalog.product')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_posts', to='marketing.promocode')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_posts', to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
