# Generated by Django 6.1.1 on 2026-10-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personalized',
            field=models.BooleanField(default=True, help_text='Recommandations basées sur les recherches et consultations'),
        ),
    ]
