# Generated by Django 6.1.1 on 2026-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='transfer_type',
            field=models.CharField(choices=[('transfer', 'Transfert'), ('return', 'Retour')], default='transfer', max_length=20),
        ),
    ]
