# Generated by Django 6.1.1 on 2026-09-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransfer_transfer_type'),
        ('store', '0005_store_facebook_store_instagram_store_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='linked_stores',
            field=models.ManyToManyField(blank=True, help_text='Boutiques supplémentaires alimentées par cet entrepôt', related_name='linked_warehouses', to='store.store'),
        ),
    ]
