# Generated by Django 6.1.1 on 2026-10-07 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_linked_stores'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Prix d'achat unitaire figé à la vente", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sessions', to='inventory.warehouse'),
        ),
    ]
