# Generated by Django 6.1.1 on 2026-10-08 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_linked_stores'),
        ('pos', '0003_backfill_pos_warehouse'),
        ('store', '0008_payslipline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('restock', models.BooleanField(default=True, help_text='Articles remis en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSRefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='possale',
            name='held_label',
            field=models.CharField(blank=True, help_text='Nom de la vente mise en attente', max_length=60),
        ),
        migrations.AddField(
            model_name='possale',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='N° de transaction carte / Mobile Money', max_length=100),
        ),
        migrations.AddField(
            model_name='possale',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='possale',
            name='refunded_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='possaleitem',
            name='refunded_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='possession',
            name='cash_count',
            field=models.JSONField(blank=True, default=dict, help_text='Comptage par coupure à la fermeture'),
        ),
        migrations.AddField(
            model_name='possession',
            name='cash_in',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Apports (hors ventes)', max_digits=12),
        ),
        migrations.AddField(
            model_name='possession',
            name='cash_out',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sorties (hors remboursements)', max_digits=12),
        ),
        migrations.AddField(
            model_name='possession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_pos_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possession',
            name='total_discounts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='possession',
            name='total_refunds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='category',
            field=models.CharField(choices=[('opening', 'Fond de caisse'), ('sale', 'Vente'), ('refund', 'Remboursement'), ('float', 'Apport de monnaie'), ('expense', 'Dépense'), ('bank_deposit', 'Dépôt banque'), ('withdrawal', 'Retrait'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('held', 'En attente'), ('completed', 'Complétée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex : Caisse 1, Comptoir entrée', max_length=60)),
                ('code', models.CharField(blank=True, help_text='Affiché sur les tickets. Ex : DLA-C1', max_length=20)),
                ('default_opening_cash', models.DecimalField(decimal_places=0, default=0, help_text="Fond de caisse proposé à l'ouverture", max_digits=12)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=10, help_text='Remise maximale accordée par un caissier (un responsable peut aller au-delà)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='store.store')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='possession',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='pos.cashregister'),
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('register',), name='pos_one_open_session_per_register'),
        ),
        migrations.AddField(
            model_name='posrefund',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posrefund',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pos.possale'),
        ),
        migrations.AddField(
            model_name='posrefund',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pos.possession'),
        ),
        migrations.AddField(
            model_name='posrefunditem',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.posrefund'),
        ),
        migrations.AddField(
            model_name='posrefunditem',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_lines', to='pos.possaleitem'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(fields=('warehouse', 'name'), name='pos_register_unique_name'),
        ),
    ]
