# Generated by Django 6.1.1 on 2026-09-23 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_enabled', models.BooleanField(default=True, verbose_name='Notifications internes')),
                ('email_order', models.BooleanField(default=True, verbose_name='Commandes')),
                ('email_rfq', models.BooleanField(default=True, verbose_name='Devis')),
                ('email_invoice', models.BooleanField(default=True, verbose_name='Factures')),
                ('email_payment', models.BooleanField(default=True, verbose_name='Paiements')),
                ('email_stock', models.BooleanField(default=False, verbose_name='Alertes stock')),
                ('email_account', models.BooleanField(default=True, verbose_name='Compte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
