# Generated by Django 6.1.1 on 2026-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_marketing',
            field=models.BooleanField(default=True, verbose_name='Offres et promotions des boutiques'),
        ),
    ]
