# Generated by Django 6.1.1 on 2026-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_notificationpreference_email_marketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='whatsapp_orders',
            field=models.BooleanField(default=True, verbose_name='WhatsApp : commandes et factures'),
        ),
    ]
