# Generated by Django 6.1.1 on 2026-10-09 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_notificationpreference_whatsapp_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order', 'Commande'), ('rfq', 'Devis'), ('invoice', 'Facture'), ('stock', 'Stock'), ('payment', 'Paiement'), ('account', 'Compte'), ('message', 'Messages'), ('system', 'Système')], default='system', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notif_user_unread_idx'),
        ),
    ]
