# Generated by Django 6.1.1 on 2026-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_stockmovement_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Prix d'achat unitaire (sert au calcul de la marge)", max_digits=12, null=True),
        ),
    ]
