# Generated by Django 6.1.1 on 2026-10-08 15:17

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Favoris existants : prix actuel comme référence (les baisses sont suivies à partir de maintenant)."""
    Wishlist = apps.get_model('catalog', 'Wishlist')
    for w in Wishlist.objects.filter(price_when_added__isnull=True).select_related('product'):
        w.price_when_added = w.product.price
        w.save(update_fields=['price_when_added'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_cost_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price_when_added',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Prix du produit au moment de l'ajout aux favoris", max_digits=12, null=True),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
