# Generated by Django 6.1.1 on 2026-10-07 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0002_invoice_warehouse'),
        ('orders', '0006_orderitem_unit_cost'),
        ('store', '0008_payslipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'instance côté Evolution API", max_length=100, unique=True)),
                ('status', models.CharField(choices=[('close', 'Déconnecté'), ('connecting', 'En attente du QR code'), ('open', 'Connecté')], default='close', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Numéro connecté (format international)', max_length=30)),
                ('profile_name', models.CharField(blank=True, max_length=200)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instance', to='store.store')),
            ],
            options={
                'verbose_name': 'Instance WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=30)),
                ('purpose', models.CharField(choices=[('order_placed', 'Confirmation de commande'), ('order_status', 'Suivi de commande'), ('seller_new_order', 'Nouvelle commande (vendeur)'), ('invoice', 'Facture'), ('test', 'Message de test')], max_length=30)),
                ('body', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Reçu'), ('read', 'Lu'), ('failed', 'Échec')], default='queued', max_length=20)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsappinstance')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='invoicing.invoice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='orders.order')),
            ],
            options={
                'verbose_name': 'Message WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
