# Generated by Django 6.1.1 on 2026-10-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='direction',
            field=models.CharField(choices=[('out', 'Envoyé'), ('in', 'Reçu')], default='out', max_length=3),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Prochain essai (vide = plus de relance)', null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='purpose',
            field=models.CharField(choices=[('order_placed', 'Confirmation de commande'), ('order_status', 'Suivi de commande'), ('seller_new_order', 'Nouvelle commande (vendeur)'), ('invoice', 'Facture'), ('test', 'Message de test'), ('reply', 'Réponse'), ('optout', 'Confirmation STOP / START'), ('inbound', 'Message reçu')], max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'En attente'), ('sending', "En cours d'envoi"), ('sent', 'Envoyé'), ('delivered', 'Reçu'), ('read', 'Lu'), ('failed', 'Échec'), ('received', 'Reçu du client')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='to_number',
            field=models.CharField(help_text='Destinataire (envoi) ou expéditeur (réception)', max_length=30),
        ),
        migrations.CreateModel(
            name='WhatsAppChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_preview', models.CharField(blank=True, max_length=200)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Client AfriMarket reconnu par son numéro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_chats', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='whatsapp.whatsappinstance')),
            ],
            options={
                'verbose_name': 'Conversation WhatsApp',
                'ordering': ['-last_message_at'],
                'unique_together': {('instance', 'number')},
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsappchat'),
        ),
        migrations.CreateModel(
            name='WhatsAppOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsappinstance')),
            ],
            options={
                'verbose_name': 'Désinscription WhatsApp',
            },
        ),
    ]
