# Generated by Django 6.1.1 on 2026-10-08 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_inbox_queue_optout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappchat',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Client Comptoir reconnu par son numéro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
