# Generated by Django 4.2.29 on 2026-03-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_store_whatsapp'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=0, help_text='Prix par unité en FCFA', max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, help_text='Prix total en FCFA', max_digits=15)),
                ('delivery_time', models.CharField(help_text='Ex: 7-10 jours', max_length=100)),
                ('payment_terms', models.CharField(default='50% à la commande, 50% à la livraison', max_length=200)),
                ('description', models.TextField(help_text='Détails de votre offre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='orders.rfq')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='store.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('rfq', 'seller')},
            },
        ),
    ]
