# Generated by Django 6.1.1 on 2026-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
