# Generated by Django 6.1.1 on 2026-10-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_loyalty_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
