# Generated by Django 6.0.3 on 2026-03-21 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_commissions', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_subscriptions', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_boosts', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_payouts', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('active_sellers', models.IntegerField(default=0)),
                ('active_buyers', models.IntegerField(default=0)),
                ('new_orders', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hosting', 'Hébergement'), ('marketing', 'Marketing'), ('salary', 'Salaires'), ('logistics', 'Logistique'), ('office', 'Bureau'), ('software', 'Logiciels'), ('other', 'Autre')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('date', models.DateField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('payment_method', models.CharField(choices=[('momo', 'MTN MoMo'), ('om', 'Orange Money'), ('bank', 'Virement bancaire')], max_length=20)),
                ('account_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Versé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_earned', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_withdrawn', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_commission_paid', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('type', models.CharField(choices=[('sale', 'Vente'), ('commission', 'Commission plateforme'), ('payout', 'Versement vendeur'), ('subscription', 'Abonnement'), ('boost', 'Boost produit'), ('refund', 'Remboursement'), ('fee', 'Frais divers')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
